"""Merge curation.json + articles_raw.json into data.js for the web app.

Validates that every blank phrase literally occurs in the fetched article
text (fails loudly instead of shipping a broken fill-in-the-blank question).
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CURATION_PATH = ROOT / "data" / "curation.json"
RAW_PATH = ROOT / "data" / "articles_raw.json"
OUTPUT_PATH = ROOT / "data.js"

SUBJECT_ID = "keiji_sosho"
SUBJECT_NAME = "刑事訴訟法"

KANJI_NUM = "〇一二三四五六七八九十百千"


def topic_id(name):
    return re.sub(r"[^0-9a-zA-Z]+", "", name.encode("ascii", "ignore").decode()) or None


def slugify(index):
    return f"{SUBJECT_ID}-topic{index:02d}"


def build_blanks(topic_name, num, text, blanks_spec, errors):
    """Validate blank answers against `text` and return (ordered_blanks,
    context_text_with_markers). Ordered by first-occurrence position so the
    UI's ①②③ numbering matches reading order. Appends to `errors` and
    returns None on any validation failure (missing text or an answer that
    is a substring of another answer in the same article, which would
    corrupt sequential marker replacement)."""
    located = []
    for b in blanks_spec:
        idx = text.find(b["answer"])
        if idx == -1:
            errors.append(
                f"{topic_name} 第{num}条: blank '{b['answer']}' not found in text"
            )
            return None
        located.append((idx, b))

    answers = [b["answer"] for _, b in located]
    for i, a in enumerate(answers):
        for j, a2 in enumerate(answers):
            if i != j and a in a2:
                errors.append(
                    f"{topic_name} 第{num}条: blank '{a}' is a substring of '{a2}' "
                    "(would corrupt marker replacement)"
                )
                return None

    located.sort(key=lambda pair: pair[0])
    ordered = [b for _, b in located]

    marker_of = {b["answer"]: f"§{i}§" for i, b in enumerate(ordered, 1)}
    context = text
    for b in sorted(ordered, key=lambda b: -len(b["answer"])):
        context = context.replace(b["answer"], marker_of[b["answer"]], 1)

    return ordered, context


def main():
    curation = json.loads(CURATION_PATH.read_text(encoding="utf-8"))
    raw = json.loads(RAW_PATH.read_text(encoding="utf-8"))

    errors = []
    topics_out = []

    # Build global distractor pools per blank category, from all curated answers.
    cat_pool = {}
    for topic in curation:
        for art in topic["articles"]:
            for b in art["blanks"]:
                cat_pool.setdefault(b["cat"], set()).add(b["answer"])

    for idx, topic in enumerate(curation, 1):
        articles_out = []
        for art in topic["articles"]:
            num = art["num"]
            entry = raw.get(num)
            if entry is None:
                errors.append(f"{topic['topic']} 第{num}条: raw text missing")
                continue
            text = entry["text"]
            result = build_blanks(topic["topic"], num, text, art["blanks"], errors)
            if result is None:
                continue
            ordered_blanks, blanks_context = result
            if num == "zenbun":
                display_num = "前文"
            elif "_" in num:
                main_no, branch_no = num.split("_")
                display_num = f"第{main_no}条の{branch_no}"
            else:
                display_num = f"第{num}条"
            articles_out.append(
                {
                    "num": num,
                    "displayNum": display_num,
                    "title": entry["title"],
                    "label": art["label"],
                    "text": text,
                    "blanks": ordered_blanks,
                    "blanksContextText": blanks_context,
                }
            )
        topics_out.append(
            {
                "id": slugify(idx),
                "name": topic["topic"],
                "category": topic["category"],
                "range": topic.get("range", ""),
                "articles": articles_out,
            }
        )

    if errors:
        print("VALIDATION ERRORS:")
        for e in errors:
            print(" -", e)
        raise SystemExit(1)

    cat_pool_out = {k: sorted(v) for k, v in cat_pool.items()}

    all_nums = [a["num"] for t in curation for a in t["articles"]]
    print(f"Total topics: {len(topics_out)}, total articles: {len(all_nums)}")

    js = (
        "// Auto-generated by scripts/build_data.py. Do not edit by hand.\n"
        "window.SUBJECT_REGISTRY = window.SUBJECT_REGISTRY || {};\n"
        f"window.SUBJECT_REGISTRY[{json.dumps(SUBJECT_ID)}] = "
        + json.dumps(
            {"id": SUBJECT_ID, "name": SUBJECT_NAME, "topics": topics_out, "catPool": cat_pool_out},
            ensure_ascii=False,
            indent=2,
        )
        + ";\n"
    )
    OUTPUT_PATH.write_text(js, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
